# Generated by Django 6.0.4 on 2026-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='напишите название блога')),
                ('description', models.TextField(blank=True, verbose_name='напиши статью')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='загрузите фото')),
                ('blog_file', models.FileField(upload_to='blog/', verbose_name='загрузите файл')),
                ('type_blog', models.CharField(choices=[('ПРОГРАММИРОВАНИЕ', 'ПРОГРАММИРОВАНИЕ'), ('БИЗНЕС', 'БИЗНЕС'), ('МЕДИЦИНА', 'МЕДИЦИНА')], default='ПРОГРАММИРОВАНИЕ', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
