# Generated by Django 6.0.4 on 2026-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_file',
            field=models.FileField(upload_to='blog/', verbose_name='загрузите pdf file'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, verbose_name='напишите статью'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='quantity',
            field=models.PositiveIntegerField(default=20, null=True, verbose_name='укажите кол-во страниц'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='type_blog',
            field=models.CharField(choices=[('Программирование', 'Программирование'), ('Бизнес', 'Бизнес'), ('Медицина', 'Медицна')], default='Программирование', max_length=100),
        ),
    ]
