# Generated by Django 6.0.4 on 2026-05-01 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='lexus rx 300', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='0_KG___', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auto.car')),
            ],
        ),
    ]
