# Generated by Django 6.0.4 on 2026-05-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_rename_number_numbercar_number_car_reviewcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcar',
            name='mark',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=100),
        ),
    ]
