# Generated by Django 6.0.4 on 2026-05-05 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_alter_numbercar_choice_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewcar',
            old_name='mark',
            new_name='marks',
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(default='Lexus RX 300', max_length=50),
        ),
        migrations.AlterField(
            model_name='numbercar',
            name='choice_car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nummer_car', to='auto.car'),
        ),
        migrations.AlterField(
            model_name='numbercar',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='numbercar',
            name='number_car',
            field=models.CharField(default='0_KG____', max_length=100),
        ),
    ]
