# Generated by Django 6.0.4 on 2026-05-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_rename_mark_reviewcar_marks_alter_car_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NumberCar',
            new_name='NummerCar',
        ),
    ]
